### ISSUE TITLE
Define stack yaml format

### ISSUE THREAD

**Issue by generalhenry** [appcelerator-archive/amp#157]
Relates to #162 

Define a minimal yaml format akin to both [stackfile](https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/) and [composefile](https://docs.docker.com/compose/compose-file/)
- **name**
  - **image**
  - environment
    - key:value
  - labels
  - public
    - name
    - protocol
    - publish_port
    - internal_port
  - replicas (default 1)

example:

``` yaml
web:
  image: appcelerator.io/amp-demo
  public:
    - name: www
      protocol: tcp
      publish_port: 80
      internal_port: 3000
  replicas: 3
  environment:
    REDIS_PASSWORD: password
redis:
  image: redis
  environment:
    - PASSWORD=password
```

**Comment by subfuzion** [comment]
We need to indicate whether the port is public or not (default=`false`), ie, publicly mapped/exposed over our reverse proxy service. For example:

``` yaml
web:
  image: appcelerator.io/amp-demo
  ports: 80:80
  public: true
```

**Comment by subfuzion** [comment]
Eventually, we will also want to be able to specify overlay networks (eg, `frontend`, `backend`).

**Comment by subfuzion** [comment]
For environment, make sure to support both forms of environment variable assignment:

``` yaml
environment:
  RACK_ENV: development
  SHOW: 'true'
  SESSION_SECRET:
```

and

``` yaml
environment:
  - RACK_ENV=development
  - SHOW=true
  - SESSION_SECRET
```

**Comment by generalhenry** [comment]
For multiple networks etc . . . I think we should punt for now, though we might want to start documenting things we will need.

As for yaml formats, that's what libs are for :)

**Comment by freignat91** [comment]
What if there is no port mapping for a given service, the syntax will be for instance;

``` yaml
web:
  image: appcelerator.io/amp-demo
  ports: :80
  public: true
```

?
I need the internal port to update ETCD for HAProxy
