### ISSUE TITLE
Parse stack yaml format

### ISSUE THREAD

**Issue by generalhenry** [appcelerator-archive/amp#161]
Relates to #162, #157

eg:

``` yaml
web:
  image: appcelerator.io/amp-demo
  ports:
    - 80:3000
  replicas: 3
  environment:
    REDIS_PASSWORD: password
redis:
  image: redis
  environment:
    - PASSWORD=password
```

into

``` go
[]Service{
  Service{
    Name: "web"
    Image: "appcelerator.io/amp-demo"
    Ports: []nat.PortMap{ "3000": nat.PortBinding{
      HostIP: ""
      HostPort: "80"
    }}
    Replicas: 3
    Environment: map[string]string{ "REDIS_PASSWORD": "password" }
  },
  Service{
    Name: "redis"
    Image: "redis"
    Environment: map[string]string{ "PASSWORD": "password" }
  },
}
```
