### ISSUE TITLE
env in stack file not working

### ISSUE THREAD

**Issue by craigivy** [appcelerator-archive/amp#272]
Env variable not being passed to docker containers.

Add single or an array of environment variables in stack file in either sample format.  Start the stack and inspect the docker containers.  Tested using both the sample files

**Comment by freignat91** [comment]
Just verified. It's works on the last amp version.
Which syntax are you using in the stack file, the right ones are:

```
environment:
  - var1 = value1
  - var2 = value2
```

or

```
environment:
  var1: value1
  var2: value2
```

step to verify using the following stack file:

```
pinger:
  image: appcelerator/pinger
  replicas: 2
pinger2:
  image: appcelerator/pinger
  replicas: 2
  environment:
    test1: aaa
    test2: bbb
  public:
    - name: www
      protocol: tcp
      internal_port: 3000
```
- amp stack up test -f [theStackFile]
- docker ps | grep test-pinger2
- get the first displayed container id
- docker exec -it [theContainerId] sh
- inside the container exec:
- set
- variables test1 and test2 are well displayed

Could you show us your stack file, perhaps there is something specific inside which makes the env not working.
