### ISSUE TITLE
Stack network stage 2

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#280]
Add networks item for services in stack file like this example: (same syntax than docker compose)

``` yaml
pinger:
  image: appcelerator/pinger
  replicas: 2
  networks:
    net1:
      aliases:
        - alias1
        - alias3
    net2:
      aliases:
        - alias2

pinger2:
  image: appcelerator/pinger
  replicas: 2
  public:
    - name: www
      protocol: tcp
      internal_port: 3000
```

so, in addition to default network (managed in stage 1), each service can join a pre-existing network
having a name and can define its alias names on this network
the pre-existing network can be shared by several stacks, enabling services communication between stacks.

then, we should have the capability to create a custom network out of service definition in stack file.
I propose this syntax, also going from docker-compose 

``` yaml
services:
   pinger:
     image: appcelerator/pinger
     replicas: 2
     networks:
        app_net:
           aliases:
           - stack1-pinger1
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1
```

**Comment by freignat91** [comment]
So stage 2:
- update stack file parsing to have two major items `services` and `networks`
- in the `services` one, add optional `networks` item in service definition with name and aliases
- in the `networks` one add full network definitions
- when executing stack file, create first the custom networks and then the services joining them to their respective networks

**Comment by freignat91** [comment]
custom networks deletion:
considering that a custom network can be define in several stack in order to enable inter-stack communication, we have to add the number of owners in the network data store in etcd.
- when a stack creates a custom network, if the network doesn't exist, we create it with an owner number equal to 1.
- when a stack creates a custom network, if the network exists and the definition is the same then we just increment the owner number, otherwise we throw an error
- when a stack is deleted, we decrement the owner number and only if this number is equal to zero, we delete the custom network.

**Comment by generalhenry** [comment]
Why deviate from

``` yaml
networks:
  outside:
    external: true
```

for external networks?

**Comment by freignat91** [comment]
@generalhenry it's change the way to manage networks declared in stack files

Either 
- (1): we think that all networks as to be created using stack files 
  or
- (2) network can be created using specific  amp command outside stack files

if we agreed on (1), it was my supposition, then we can't use external syntax, because each stack should be able to create the external network. We can't have the definition in 1 and just the external link in two other, because if we want to start only the two orther, we don't have the network definition to create it first.

if we agreed on (2), then ok, we can have only external syntax in stack files and network definition elsewhere.

Now we could have both (1) and (2): Accept also external syntax to include other networks created out of amp or using amp network creation command. The difference with custom networls is that the external networks won't be deleted by the stack rm command and then need a specific management, but it's actually complementary.

**Comment by generalhenry** [comment]
So to confirm.

Each stack would have it's own `[default network]` that's stack scoped.
If you specify a network in the stack file you then create a `[custom network]` that's swarm scoped? (or perhaps organization or team scoped?)

Follow up:
  How would conflicts in network definitions be handled? eg:

_web-stack.yml_

``` yaml
services:
  web:
    image: web
    networks:
      app_net
  admin:
    image: web-admin
    networks:
      app_net
networks:
  app_net:
    driver: bridge
```

_data-stack.yml_

``` yaml
services:
  redis:
    image: redis
    networks:
      app_net:
        aliases:
          - db
  admin:
    image: redis-admin
networks:
  app_net:
    driver: overlay
```
