### ISSUE TITLE
amp network stage 3

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#313]
As Henry suggest in #280, it's interesting to be able to make stack services join external network already created. Stack file syntax could be the same than docker compose file one, for instances:

```
services:
  myservice:
     networks:
        anexternalnetwork
networks:
   anexternalnetwork:
     external: true
```

or

```
services:
  myservice:
     networks:
        myexternalnetwork
networks:
   myexternalnetwork:
     external:
        name: anexternalnetwwork
```

In both case, service `myservice` will join the external already created network `anexternalnetwork`, in case one, the true name of the external network is used in the stack file, in the case two, the service use an external network name valid only in the stack file and reference the true external network name in the external section.

External network won't be manage by amp for now. So they have to be created/deleted out of amp. Perhaps later (amp network stage 4) we could add full external network management in amp.
