### ISSUE TITLE
Non reproducibility of CLI tests

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#374]
Ref #370 

CLI tests are passing ~ half of the times.
One reason may be because the test specs files contains ordered commands that are not executed in order.

Specs:

```
    grep "^[^ ]" ./cmd/amp/cli/test_samples/09-remove-stack.yml  
    stop-stack:
    remove-stack:
    list-stack:
```

Results:

```
    cli_test.go:41: test 09-remove-stack.yml
    cli_test.go:82: [amp stack ls] Command passed.
    cli_test.go:84: [amp stack ls] Running...
    cli_test.go:85: [amp stack ls] Iteration: 1
    cli_test.go:109: [amp stack ls] Error: miss matched expectation
    cli_test.go:82: [amp stack stop stack1] Command passed.
    cli_test.go:84: [amp stack stop stack1] Running...
    cli_test.go:85: [amp stack stop stack1] Iteration: 1
    cli_test.go:113: [amp stack stop stack1] Command result:
             c36915de96d73f28347551221745e525e26643d225a9c6147348c0a300565d4c

    cli_test.go:82: [amp stack rm stack1] Command passed.
    cli_test.go:84: [amp stack rm stack1] Running...
    cli_test.go:85: [amp stack rm stack1] Iteration: 1
    cli_test.go:113: [amp stack rm stack1] Command result:
             c36915de96d73f28347551221745e525e26643d225a9c6147348c0a300565d4c
```

This is because [iterating on a map with range does not guarantee the order](https://blog.golang.org/go-maps-in-action#TOC_7.).

**Comment by generalhenry** [comment]
Why not a to level array? eg:

``` yaml
- remove-service:
  cmd: amp service rm
  args:
    - pinger
  options:
  expectation: (pinger)
- list-service:
  cmd: docker service ls
  args:
  options:
  expectation: ((ID)(\s)+(NAME)(\s)+(REPLICAS)(\s)+(IMAGE)(\s)+(COMMAND)((.)|(\s))+)
```
