### ISSUE TITLE
add Portainer, the Docker UI in ampcore

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#744]
add Portainer, the Docker UI in ampcore, adding:
```
    dockerui:
        image: portainer/portainer
        deploy:
            mode: replicated
            replicas: 1
            labels:
                io.amp.role: "infrastructure"
            placement:
                constraints: [node.role == manager]
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - infra 
```
in ampcore.yml and updated haproxy to route ui.ampcore.local.appcelerator.io to it
It's a nice UI useful to see the amp cluster state, easy to integrate

we also could create a dedicated stack for it (ampui.stack) to do not have it in ampccore by default.
